from pathlib import Path
for path in ['src/Inventory/Infrastructure/Doctrine/DbalHomeProductIdentityRepairStore.php','src/Synchronization/Infrastructure/Doctrine/DbalSyncStore.php']:
    p=Path(path);s=p.read_text().replace('/** @param array<string, mixed> $row @return array<string, mixed> */','/**\n     * @param array<string, mixed> $row\n     * @return array<string, mixed>\n     */');p.write_text(s)
p=Path('tests/Integration/HomeProductIdentityReconciliationTest.php');s=p.read_text().replace('$this->db->transactional($operation)', '$this->db->transactional(static fn (): mixed => $operation())');p.write_text(s)
p=Path('tests/Unit/Catalog/CatalogImportServiceTest.php');s=p.read_text();a=s.index('public function testConfirmationPublishesEveryCreatedHomeProductToTheChangeFeed');b=s.index('\n    public function ',a+30);part=s[a:b];part=part.replace("                'productName' => null,\n",'');part=part.replace("                'privateName' => null,", "                'privateName' => null,\n                'productName' => 'Synthetic product family',");p.write_text(s[:a]+part+s[b:])
p=Path('tests/Integration/HomeProductIdentityReconciliationTest.php');s=p.read_text();prefix=s[:s.index('final class HomeProductIdentityReconciliationTest')];a=s.index('final readonly class IdentityRepairTransactionManager');b=s.index('final class IdentityRepairUuidGenerator');Path('tests/Integration/IdentityRepairTransactionManager.php').write_text(prefix+s[a:b].strip()+'\n');Path('tests/Integration/IdentityRepairUuidGenerator.php').write_text(prefix+s[b:].strip()+'\n');s=s[:a].rstrip()+'\n';s=s.replace('quantity TEXT, raw_description TEXT)', 'quantity TEXT,\n             raw_description TEXT)');lines=[]
for line in s.splitlines():
    if len(line)>110 and 'self::assertSame(' in line:
        line=line.replace('self::assertSame(', 'self::assertSame(\n            ').replace(', ', ',\n            ')
    lines.append(line)
p.write_text('\n'.join(lines)+'\n')
p=Path('src/AiIntegration/Application/AiTransmissionPlan.php');p.write_text(p.read_text().replace("throw new Problem(409, 'AI setup required', 'Select saved, revisioned provider profiles before extraction.');", "throw new Problem(\n                409,\n                'AI setup required',\n                'Select saved, revisioned provider profiles before extraction.',\n            );"))
p=Path('src/Inventory/Infrastructure/Cli/ReconcileHomeProductIdentitiesCommand.php');s=p.read_text();s=s.replace("#[AsCommand(name: 'inventory:reconcile-identities', description: 'Preview or explicitly apply bounded home-product identity repairs.')]", "#[AsCommand(\n    name: 'inventory:reconcile-identities',\n    description: 'Preview or explicitly apply bounded home-product identity repairs.',\n)]");s=s.replace("$limit = filter_var($input->getOption('limit'), FILTER_VALIDATE_INT, ['options' => ['min_range' => 1, 'max_range' => 1000]]);", "$limit = filter_var(\n            $input->getOption('limit'),\n            FILTER_VALIDATE_INT,\n            ['options' => ['min_range' => 1, 'max_range' => 1000]],\n        );");s=s.replace("$output->writeln('<error>Use --home UUID [--after UUID] [--limit 1..1000]; --apply requires --actor UUID.</error>');", "$output->writeln(\n                '<error>Use --home UUID [--after UUID] [--limit 1..1000]; --apply requires --actor UUID.</error>',\n            );");s=s.replace("preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i', $value)", "preg_match(\n            '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i',\n            $value,\n        )");p.write_text(s)
p=Path('src/Inventory/Infrastructure/Doctrine/DbalHomeProductIdentityRepairStore.php');p.write_text(p.read_text().replace("$this->connection->fetchOne('SELECT product_id FROM product_packs WHERE id = :id', ['id' => $pack])", "$this->connection->fetchOne(\n                'SELECT product_id FROM product_packs WHERE id = :id',\n                ['id' => $pack],\n            )"))
p=Path('src/Inventory/Infrastructure/Factory/InventoryFactory.php');s=p.read_text().replace('use Providentia\\Inventory\\Infrastructure\\Cli\\ReconcileHomeProductIdentitiesCommand;', 'use Providentia\\Inventory\\Infrastructure\\Cli\\ReconcileHomeProductIdentitiesCommand as RepairIdentitiesCommand;');s=s.replace('ReconcileHomeProductIdentitiesCommand::class', 'RepairIdentitiesCommand::class').replace('new ReconcileHomeProductIdentitiesCommand(', 'new RepairIdentitiesCommand(');p.write_text(s)
p=Path('tests/Unit/Inventory/InventoryServiceTest.php');s=p.read_text().replace("$store->expects(self::once())->method('homeProduct')->with(self::HOME_ID, self::PRODUCT_ID)->willReturn($record);", "$store->expects(self::once())\n            ->method('homeProduct')\n            ->with(self::HOME_ID, self::PRODUCT_ID)\n            ->willReturn($record);");p.write_text(s)
# xargs maps nonzero tool exits to 123; call the formatter directly instead.
import subprocess
subprocess.run(['git','add','-N','src','tests'],check=True)
files=subprocess.check_output(['git','diff','--name-only','--','*.php'],text=True).splitlines()
result=subprocess.run(['vendor/bin/phpcbf',*files]).returncode
assert result in (0,1,2), result
