#!/usr/bin/env bash

set -Eeuo pipefail

readonly script_directory="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly project_directory="$(cd -- "$script_directory/.." && pwd)"
readonly requirements="$script_directory/agent-requirements.json"
readonly agent_state="$project_directory/.agent-tools"
readonly agent_env="$project_directory/.agent-env"
readonly agent_image="providentia-backend-agent:php-8.5.9"

usage() {
  cat <<'EOF'
Usage: tools/agent-setup.sh [--check|--doctor]
  no argument  Install missing Linux prerequisites and build the pinned agent image.
  --check      Validate the checked-in environment contract without mutation.
  --doctor     Provision the environment and run the complete local quality/build lane.
EOF
}

require_linux() {
  if [[ "$(uname -s)" != Linux ]]; then
    echo 'The automated agent bootstrap currently supports Linux hosts.' >&2
    exit 69
  fi
}

validate_contract() {
  command -v node >/dev/null || {
    echo 'Node.js is required for the non-mutating setup-contract check.' >&2
    exit 69
  }
  node - "$requirements" "$project_directory" <<'NODE'
const fs = require('node:fs');
const path = require('node:path');
const [manifestPath, root] = process.argv.slice(2);
const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
if (manifest.schemaVersion !== 1 || manifest.repositoryRole !== 'backend') {
  throw new Error('Unexpected agent requirements schema or repository role.');
}
const expected = {
  php: '8.5.9', composer: '2.10.2', redisExtension: '6.3.0', xdebug: '3.5.3',
};
for (const [key, value] of Object.entries(expected)) {
  if (manifest.runtime?.[key] !== value) {
    throw new Error(`Unexpected ${key} pin: ${manifest.runtime?.[key]}`);
  }
}
for (const domain of [
  'repo.packagist.org', 'pecl.php.net', 'registry-1.docker.io', 'ghcr.io',
]) {
  if (!manifest.networkAllowlist?.includes(domain)) {
    throw new Error(`Agent network allowlist is missing ${domain}.`);
  }
}
for (const command of [
  'composer check',
  'composer test:coverage && composer coverage:check',
  'composer test:mutation',
  'composer audit --locked',
]) {
  if (!manifest.validation?.includes(command)) {
    throw new Error(`Agent validation lane is missing: ${command}`);
  }
}
const dockerfile = fs.readFileSync(path.join(root, 'infrastructure/agent/Dockerfile'), 'utf8');
for (const pin of [
  'php:8.5.9-cli-alpine3.23',
  'composer:2.10.2',
  'REDIS_EXTENSION_VERSION=6.3.0',
  'XDEBUG_VERSION=3.5.3',
]) {
  if (!dockerfile.includes(pin)) throw new Error(`Agent Dockerfile is missing ${pin}.`);
}
NODE
  bash -n "$script_directory/agent-setup.sh"
  echo 'Agent development environment contract verified.'
}

install_system_packages() {
  mapfile -t packages < <(
    node -e '
      const fs = require("node:fs");
      const manifest = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      process.stdout.write(manifest.linux.aptPackages.join("\n"));
    ' "$requirements"
  )
  local missing=()
  local package
  for package in "${packages[@]}"; do
    if ! dpkg-query -W -f='${Status}' "$package" 2>/dev/null | grep -q 'ok installed'; then
      missing+=("$package")
    fi
  done
  if (( ${#missing[@]} == 0 )); then
    echo 'Linux prerequisites are already installed.'
    return
  fi
  local privilege=()
  if (( EUID != 0 )); then
    command -v sudo >/dev/null || {
      printf 'Missing Linux packages and sudo is unavailable: %s\n' "${missing[*]}" >&2
      exit 77
    }
    privilege=(sudo)
  fi
  "${privilege[@]}" apt-get update
  "${privilege[@]}" apt-get install --yes --no-install-recommends "${missing[@]}"
}

require_docker_daemon() {
  if docker info >/dev/null 2>&1; then
    return
  fi
  if command -v systemctl >/dev/null 2>&1; then
    if (( EUID == 0 )); then
      systemctl start docker 2>/dev/null || true
    elif command -v sudo >/dev/null 2>&1; then
      sudo systemctl start docker 2>/dev/null || true
    fi
  fi
  docker info >/dev/null 2>&1 || {
    cat >&2 <<'EOF'
Docker is installed but this shell cannot reach its daemon. Start Docker and
grant the current user access to the Docker socket, then rerun the bootstrap.
EOF
    exit 69
  }
  docker compose version >/dev/null
}

write_environment() {
  mkdir -p "$agent_state"
  {
    echo '# Generated by tools/agent-setup.sh; do not commit.'
    printf 'export PROVIDENTIA_BACKEND_ROOT=%q\n' "$project_directory"
    printf 'export PROVIDENTIA_BACKEND_AGENT_IMAGE=%q\n' "$agent_image"
  } > "$agent_env"
  echo "Generated $agent_env"
}

pull_pinned_images() {
  mapfile -t images < <(
    node -e '
      const fs = require("node:fs");
      const manifest = JSON.parse(fs.readFileSync(process.argv[1], "utf8"));
      process.stdout.write(manifest.containerImages.join("\n"));
    ' "$requirements"
  )
  local image
  for image in "${images[@]}"; do
    docker pull "$image"
  done
}

build_agent_image() {
  docker build \
    --file "$project_directory/infrastructure/agent/Dockerfile" \
    --tag "$agent_image" \
    "$project_directory"
}

setup() {
  require_linux
  validate_contract
  install_system_packages
  require_docker_daemon
  write_environment
  pull_pinned_images
  build_agent_image
}

run_in_agent() {
  docker run --rm "$agent_image" "$@"
}

doctor() {
  setup
  cd "$project_directory"
  bash tests/structural/verify.sh
  run_in_agent composer check
  docker run --rm -e XDEBUG_MODE=coverage "$agent_image" sh -lc \
    'composer test:coverage && composer coverage:check'
  docker run --rm -e XDEBUG_MODE=coverage "$agent_image" \
    composer test:mutation
  run_in_agent composer audit --locked
  docker compose \
    --profile sqlite --profile mysql --profile mariadb \
    --profile redis --profile valkey config --quiet
  docker run --rm \
    -e DATABASE_URL=sqlite:///var/agent.sqlite \
    -e QUEUE_REQUIRED=0 \
    "$agent_image" \
    sh -lc 'php bin/doctrine-migrations migrations:migrate --no-interaction && php bin/providentia foundation:prove agent'
  docker build --tag providentia-source-agent "$project_directory"
  docker build --file Dockerfile.production --target runtime \
    --tag providentia-runtime-agent "$project_directory"
  docker build --file Dockerfile.production --target media-worker \
    --tag providentia-media-agent "$project_directory"
  docker build --file Dockerfile.production --target web \
    --tag providentia-web-agent "$project_directory"
  echo 'Backend agent doctor passed all local quality, migration, and image-build gates.'
}

case "${1:-}" in
  '') setup ;;
  --check) validate_contract ;;
  --doctor) doctor ;;
  --help|-h) usage ;;
  *) usage >&2; exit 64 ;;
esac
